# Generated by Django 5.0.7 on 2024-07-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='date',
            new_name='data_nascimento',
        ),
    ]
